/**
 * Visitor presence.
 *
 * The owner opens this page to answer one question: **is anybody reading?**
 * This module answers that question and nothing else.
 *
 * ## What is stored, and what cannot be
 *
 * Two facts per visitor: a random id the browser generated, and the moment it
 * was last seen. There is no column for an address, a device, a user agent, a
 * referrer, a viewport, a cookie or a fingerprint to go in, which is the whole
 * argument. "We do not collect your IP" is a promise about behaviour and can be
 * broken by a later commit; "there is nowhere to put it" is a claim about the
 * shape of the data, and shape does not change on a Tuesday afternoon when
 * somebody adds a column.
 *
 * The id is 128 bits from `crypto.getRandomValues`, generated in the browser and
 * kept in `localStorage`. It is **not** derived from the machine, so it is not a
 * fingerprint wearing a different name, and it is not a cookie, so nothing else
 * on the internet can read it and nothing here can correlate it with another
 * site. Two browsers, one person, two unrelated ids. The cost is stated plainly
 * rather than hidden: the same visitor in a private window is a stranger, and
 * that is the price of being untrackable across sites.
 *
 * This is the same discipline as `theme_feedback` and for the same reason — a
 * last-seen timestamp is not identifying until something else is added to it.
 *
 * ## Why the owner has an availability state at all
 *
 * "How many people are online" is answered for a live board. "Can I answer right
 * now" is a different question with a different failure mode: a console left
 * open on a laptop in a bag would claim to be answering for as long as the
 * laptop was awake. So the owner's availability expires — an hour without
 * activity is idle, and a sign-out is immediate, because both are facts about
 * the *session* rather than about the last message received.
 *
 * The module is pure: no framework, no Supabase, and no clock of its own. Every
 * rule below takes the current time from its caller, so each one is testable
 * without a browser, a database or a fake timer.
 */

/* -------------------------------------------------------------------------
 * The session id
 * ---------------------------------------------------------------------- */

/**
 * How many hexadecimal characters, and therefore how many bits.
 *
 * 32 characters is 128 bits: more than a uuid, generated by the same call the
 * browser already makes for one, and with no dashes to be normalised somewhere
 * else. The length is a check rather than a hint because this value becomes a
 * primary key, a URL parameter and a rate-limit bucket, and the cheapest way to
 * refuse all three at the boundary is one anchored pattern.
 */
export const PRESENCE_SESSION_ID_LENGTH = 32;

/**
 * The only shape a session id may take, in the domain and in the database.
 *
 * Mirrored by a `check` constraint on `visitor_presence.session_id` rather than
 * imported, so a mismatch between the two is detectable instead of invisible;
 * `tests/unit/domain/presence.test.ts` asserts they agree.
 */
export const PRESENCE_SESSION_ID_PATTERN = /^[0-9a-f]{32}$/;

/**
 * A random, browser-generated, per-browser-profile identifier.
 *
 * A plain `string` with a rule attached rather than a branded type, because the
 * only thing that makes it trustworthy is {@link isPresenceSessionId} and a brand
 * would let an unchecked cast into the type look like a checked one.
 */
export type PresenceSessionId = string;

/**
 * Whether a value may be used as a session id.
 *
 * Called at every boundary — the heartbeat route, the conversation route, the
 * repository — because the value arrives as `unknown` from JSON, a query string
 * or a database row, and a value that skips this check is a value that becomes
 * a primary key.
 */
export function isPresenceSessionId(value: unknown): value is PresenceSessionId {
  return typeof value === "string" && PRESENCE_SESSION_ID_PATTERN.test(value);
}

export class InvalidPresenceSessionIdError extends Error {
  constructor(value: unknown) {
    super(
      `Refusing to track a session whose id is not ${PRESENCE_SESSION_ID_LENGTH} lowercase hex characters: ${String(value)}`,
    );
    this.name = "InvalidPresenceSessionIdError";
  }
}

/* -------------------------------------------------------------------------
 * Visitor presence
 * ---------------------------------------------------------------------- */

/** How often a page says "I am still here". */
export const PRESENCE_HEARTBEAT_MS = 60_000;

/**
 * How long a heartbeat counts as "online".
 *
 * Three beats, not one. A browser in a background tab has its timers throttled
 * to roughly once a minute and a sleeping laptop sends nothing at all, so a
 * one-beat window would report a reader who is still reading as gone the moment
 * they switched tabs. The cost of three minutes is that someone who closed the
 * laptop is listed as online for up to three minutes; the cost of one is that
 * the board is wrong constantly, which is worse for a board whose only job is
 * to be believed.
 */
export const PRESENCE_ONLINE_WINDOW_MS = 3 * 60_000;

/**
 * How long a session row survives after the last heartbeat.
 *
 * A day. Long enough for the owner to come back to a conversation the next
 * morning and still see who was there, short enough that the table describes
 * roughly one working day of visitors rather than accumulating every reader the
 * site has ever had. Rows are deleted, not marked: "forgotten" has to mean the
 * row is gone, or it is a retention policy with extra steps.
 */
export const PRESENCE_RETENTION_MS = 24 * 60 * 60_000;

/**
 * How many rows one board read can return.
 *
 * A cap that does not grow with the table. Someone who opens the console during
 * a launch must not be able to make the response grow with traffic, and the
 * board shows the newest sessions, which are the ones a live conversation is
 * about.
 */
export const MAX_PRESENCE_ROWS = 200;

export const PRESENCE_STATES = ["online", "offline"] as const;

export type PresenceState = (typeof PRESENCE_STATES)[number];

/**
 * One visitor's row.
 *
 * Every field is a time or a counter derived from a time. There is no field a
 * device, an address or a fingerprint could be written into, and that is the
 * reason the port in `src/application/presence/track-visitors.ts` has this shape.
 */
export type PresenceSession = {
  readonly sessionId: PresenceSessionId;
  readonly firstSeenAt: number;
  readonly lastSeenAt: number;
  readonly heartbeatCount: number;
};

/**
 * A heartbeat, as the repository receives it.
 *
 * Deliberately narrower than {@link PresenceSession}: a write never carries
 * `firstSeenAt` or a count, because both are the repository's to derive. A port
 * that accepted them would let a caller claim a session was first seen last week.
 */
export type PresenceHeartbeat = {
  readonly sessionId: PresenceSessionId;
  readonly sentAt: number;
};

/** Whether this session is inside the online window. */
export function isOnline(session: PresenceSession, now: number): boolean {
  return presenceState(session, now) === "online";
}

/**
 * Online or offline, and the two answers mean opposite things.
 *
 * A future timestamp — a clock skewed ahead of the server's, or a row written by
 * a misconfigured job — is treated as online rather than as an arithmetic
 * accident, because "seen in the future" is much more likely to be a live browser
 * whose clock is wrong than a visitor from the future.
 */
export function presenceState(session: PresenceSession, now: number): PresenceState {
  return now - session.lastSeenAt < PRESENCE_ONLINE_WINDOW_MS ? "online" : "offline";
}

/** Whether the row is old enough to be deleted rather than displayed. */
export function isForgettable(session: PresenceSession, now: number): boolean {
  return now - session.lastSeenAt >= PRESENCE_RETENTION_MS;
}

/** The cutoff to hand a delete: everything strictly older than this goes. */
export function forgettableBefore(now: number): number {
  return now - PRESENCE_RETENTION_MS;
}

/** One row as the board renders it: the state, and the time it was decided. */
export type VisitorPresence = {
  readonly sessionId: PresenceSessionId;
  readonly state: PresenceState;
  readonly lastSeenAt: number;
  readonly firstSeenAt: number;
  /** True once the session is inside the online window. */
  readonly isOnline: boolean;
};

/** The board's own numbers, derived rather than counted by a query. */
export type PresenceCounts = {
  readonly online: number;
  readonly total: number;
  /** The most recent heartbeat across every row, or `null` when nobody is here. */
  readonly newestSeenAt: number | null;
};

/**
 * Turns rows into rows the board can render, and drops what the retention window
 * has already forgotten.
 *
 * A delete and a filter are both applied. The delete keeps the table small; this
 * keeps the answer honest in the window between a visitor going quiet and the
 * sweep catching up — a row nobody has swept is not a reason to keep showing
 * someone from three days ago.
 */
export function toVisitorPresence(
  sessions: ReadonlyArray<PresenceSession>,
  now: number,
): VisitorPresence[] {
  return sessions
    .filter((session) => !isForgettable(session, now))
    .slice(0, MAX_PRESENCE_ROWS)
    .map((session) => {
      const state = presenceState(session, now);

      return {
        sessionId: session.sessionId,
        state,
        lastSeenAt: session.lastSeenAt,
        firstSeenAt: session.firstSeenAt,
        isOnline: state === "online",
      };
    });
}

/** The count the console leads with, so it cannot disagree with the list. */
export function summarisePresence(visitors: ReadonlyArray<VisitorPresence>): PresenceCounts {
  let online = 0;
  let newestSeenAt: number | null = null;

  for (const visitor of visitors) {
    if (visitor.isOnline) {
      online += 1;
    }

    if (newestSeenAt === null || visitor.lastSeenAt > newestSeenAt) {
      newestSeenAt = visitor.lastSeenAt;
    }
  }

  return { online, total: visitors.length, newestSeenAt };
}

/* -------------------------------------------------------------------------
 * The owner's own availability
 * ---------------------------------------------------------------------- */

/**
 * How long the owner stays "can answer" without doing anything.
 *
 * An hour. Long enough to cover a meeting, a train and a lunch without the
 * console lying about being available; short enough that a laptop closed at a
 * desk does not advertise an owner who is not there. The alternative — a session
 * that is live until it is closed — is a claim the site cannot verify, and an
 * unanswered visitor deserves better than a promise.
 */
export const OWNER_IDLE_AFTER_MS = 60 * 60_000;

export const OWNER_ACTIVITY_STATES = ["answering", "idle", "signed-out"] as const;

export type OwnerActivityState = (typeof OWNER_ACTIVITY_STATES)[number];

/**
 * The owner's row.
 *
 * Two nullable timestamps and nothing else. `signedOutAt` exists so that a
 * sign-out is a *fact* rather than an absence: without it, a console closed at
 * a desk and a console closed by signing out would be indistinguishable, and
 * the second one would keep claiming to be available for an hour.
 *
 * `lastActivityAt` is stamped by every authenticated owner request, so "activity"
 * is the console being open and looked at — not a claim the owner has to
 * maintain.
 */
export type OwnerPresence = {
  readonly lastActivityAt: number | null;
  readonly signedOutAt: number | null;
};

/** The state before anything has ever been recorded. */
export const NO_OWNER_PRESENCE: OwnerPresence = {
  lastActivityAt: null,
  signedOutAt: null,
};

/**
 * Whether the owner is showing as able to answer.
 *
 * Three states, in the order they are decided, and the order is the design:
 *
 * 1. **Signed out** — either never signed in, or a sign-out at or after the last
 *    activity. Checked first because it is the only one that must be immediate:
 *    a stale `lastActivityAt` from a session that has ended must not be able to
 *    outvote it.
 * 2. **Idle** — an hour with no authenticated request.
 * 3. **Answering** — a live session inside the hour.
 */
export function ownerActivityState(presence: OwnerPresence, now: number): OwnerActivityState {
  if (presence.lastActivityAt === null) {
    return "signed-out";
  }

  if (presence.signedOutAt !== null && presence.signedOutAt >= presence.lastActivityAt) {
    return "signed-out";
  }

  return now - presence.lastActivityAt < OWNER_IDLE_AFTER_MS ? "answering" : "idle";
}

/**
 * The rule the console labels with, as a boolean.
 *
 * Separate from {@link ownerActivityState} so the *predicate* cannot drift from
 * the label: a caller asking "can I answer" gets the answer, and the three-state
 * version exists for the badge that has to name which of the two no-answers it is.
 */
export function canOwnerAnswer(presence: OwnerPresence, now: number): boolean {
  return ownerActivityState(presence, now) === "answering";
}

/** Stamps activity. Activity always wins over an earlier sign-out. */
export function recordOwnerActivity(presence: OwnerPresence, at: number): OwnerPresence {
  return { lastActivityAt: at, signedOutAt: null };
}

/**
 * Records a sign-out.
 *
 * Only moves the clock forward: an out-of-order write must not resurrect a
 * session that has already ended, and the route that records this runs on a 401
 * that may race with a poll that succeeded.
 */
export function recordOwnerSignOut(presence: OwnerPresence, at: number): OwnerPresence {
  if (presence.signedOutAt !== null && presence.signedOutAt > at) {
    return presence;
  }

  return { lastActivityAt: presence.lastActivityAt, signedOutAt: at };
}
